version: "3"
services:
  bendungan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bendungan-container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=mysql-db1
      - MYSQL_DATABASE=bendungan
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password

  wohhale:
    build:
      context: ../WOHHALE
      dockerfile: Dockerfile
    container_name: wohhale-container
    ports:
      - "8000:80"
    volumes:
      - ../WOHHALE:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=mysql-db2
      - MYSQL_DATABASE=wohhale
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password

  mysql-db1:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bendungan
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always

  mysql-db2:
    image: mysql:latest
    container_name: mysql-wohhale
    ports: 
     - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wohhale
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always
