version: "3"
services:
  bendungan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bendungan-container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=mysql-db1
      - MYSQL_DATABASE=bendungan
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password

  websitert7:
    build:
      context: ../WebsiteRT7
      dockerfile: Dockerfile
    container_name: websitert7-container
    ports:
      - "81:80"
    volumes:
      - ../WebsiteRT7:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=mysql-db2
      - MYSQL_DATABASE=websitert7
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password

  mysql-db1:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bendungan
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always

  mysql-db2:
    image: mysql:latest
    container_name: mysql-websitert7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: websitert7
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always
