version: "3"
services:
  db-bendungan:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bendungan
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  db-websitert7:
    image: mysql:latest
    container_name: mysql-websitert7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: websitert7
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    networks:
      - mynetwork2
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: bendungan:1.0
    container_name: bendungan-container
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bendungan
      DB_USERNAME: root
      DB_PASSWORD: password
  laravel-apps:
    build:
      context: ./WebisteRT7
    image: wohhale:1.0
    container_name: wohhale-container
    ports: -"81:80"
    depends_on:
      - db
    networks:
      - mynetwork2
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_DATABASE: websitert7
      DB_USERNAME: root
      DB_PASSWORD: password

networks:
  mynetwork:
    driver: bridge
  mynetwork2:
    driver: bridge
