version: "3"
services:
  bendungan:
    build:
      context: .
      dockerfile: Dockerfile
    image: bendungan:1.0
    container_name: bendungan-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/bendungan
    restart: always
    environment:
      - MYSQL_HOST=mysql-db1
      - MYSQL_DATABASE=bendungan
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password
    networks:
      - bendungan
  mysql-db1:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bendungan
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - bendungan
      
  wohhale:
    build:
      context: ../WOHHALE
      dockerfile: Dockerfile
    image: wohhale:1.0
    container_name: wohhale-container
    ports:
      - "8000:80"
    volumes:
      - ../WOHHALE:/var/www/html/wohhale
    restart: always
    environment:
      - MYSQL_HOST=mysql-db2
      - MYSQL_DATABASE=wohhale
      - MYSQL_USER=fredo
      - MYSQL_PASSWORD=password
    networks:
      - wohhale

  mysql-db2:
    image: mysql:latest
    container_name: mysql-wohhale
    ports: 
     - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wohhale
      MYSQL_USER: fredo
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - wohhale

networks:
  bendungan:
    driver: bridge
  wohhale:
    driver: bridge